#!/bin/bash
DELAY=30
while (true) ; do
  echo "------------------------------------------------------------"
  echo "`date` --------------- `find ~/wosCache -type f | wc -l` files in cache"
  #tput sgr0
  #tput setaf 4
  EMPTY=true
  IFS=$'\n' && for i in $(find ~irods/wosCache/live/rd009a -type f -mmin +30) ; do
    if fuser "$i" 2>/dev/null >/dev/null ; then
      echo "`tput setaf 1`Open: `stat -c "%s" $i | numfmt --to=iec` $i`tput sgr0`";
    else 
      doubleQuoteEscaped=`echo $i | sed -e 's/\x22/\\\x22/'`
      #echo "doubleQuoteEscaped=$doubleQuoteEscaped"
      DID=`iquest "%s" "select DATA_ID where DATA_PATH = '$doubleQuoteEscaped'"`
      if [ "$DID" -eq "$DID" ] 2>/dev/null; then
        WOID=`iquest "%s" "select DATA_PATH where DATA_ID = '$DID' and DATA_RESC_HIER = 'wos;wosArchive'"`
        if [[ $WOID =~ ^CAT_NO_ROWS_FOUND.*$ ]] ; then
          tput setab 1; tput setaf 0
          echo "DATA_ID $DID, not in WOS: $i"
          irule -F ./DirectTrimThis.r *DATA_ID=\"$DID\"
          #irule -F ./SyncThis.r *DATA_ID=\"$DID\"
          tput sgr0
        else
          #Found WOS version of file
          WSIZE=`curl -sI 10.10.200.74/objects/$WOID | grep Content-Length | cut -c17- | tr -d '[:space:]'`
          ISIZE=`iquest "%s" "select DATA_SIZE where DATA_ID = '$DID' and DATA_RESC_HIER = 'wos;wosArchive'"`
          if [ $(($WSIZE)) -eq $(($ISIZE)) ] ; then 
            echo "`tput setaf 3`DATA_ID ${DID}, `stat -c "%s" $i | numfmt --to=iec` /rdZone/`echo $i | cut -c25-``tput sgr0`"
            irule -F ./DirectTrimThis.r *DATA_ID=\"$DID\"
            EMPTY=false
          else 
            tput setab 6; tput setaf 0
            echo "DATA_ID $DID, size mismatch iRODS($ISIZE) and WOS($WSIZE) for /rdZone/`echo $i | cut -c25-``tput sgr0`"
            tput sgr0
          fi
        fi
      else
        tput setab 1; tput setaf 0
        echo "Not in ICAT $i"
        tput sgr0
      fi
    fi
  done
  printf "`tput bold`Trim finished....`date '+%d/%m/%Y %H:%M:%S'`\n`tput sgr0`"
  #echo "Pruning empty directories in cache..."
  find ~irods/wosCache -type d -empty -exec rmdir {} +
  #./lsWriting
  if $EMPTY ; then
    tput setaf 2
    secs=$((5 * 60))
    IFS=''
    if [ -t 0 ]; then stty -echo -icanon raw time 0 min 0; fi
    while [ -z "$key" -a $secs -gt 0 ]; do
        read key
        echo -ne "No files in cache to be processed - sleeping $secs\033[0K\r"
        sleep 1
        : $((secs--))
    done
    key=""
    if [ -t 0 ]; then stty sane; fi
    tput sgr0
  fi
done
